@echo off
echo Starting BuildLedger Microservices...

echo Starting Eureka Server (PORT 8761)...
start "Eureka Server" cmd /k "cd buildledger-eureka-server && mvn spring-boot:run"
echo Waiting for Eureka to initialize...
timeout /t 15

echo Starting API Gateway (PORT 8080)...
start "API Gateway" cmd /k "cd buildledger-api-gateway && mvn spring-boot:run"
echo Waiting for Gateway to initialize...
timeout /t 15

echo Starting IAM Service (PORT 8081)...
start "IAM Service" cmd /k "cd buildledger-iam\iam-service && mvn spring-boot:run"

echo Starting Vendor Service (PORT 9090)...
start "Vendor Service" cmd /k "cd vendormanagement\Buildledger-main && mvn spring-boot:run"

echo Starting Contract Creation Service (PORT 8082)...
start "Contract Creation Service" cmd /k "cd contractmanagement\contractcreation && mvn spring-boot:run"

echo Starting Delivery Service (PORT 8084)...
start "Delivery Service" cmd /k "cd deliverService && mvn spring-boot:run"

echo Starting Compliance Audit Service (PORT 8085)...
start "Compliance Audit Service" cmd /k "cd compliance-audit-service && mvn spring-boot:run"

echo All services are starting up in separate terminal windows!
echo Please check the individual windows for logs and wait a moment for them to sync with Eureka.
